### ISSUE TITLE
change menu to drop down

### ISSUE THREAD

**Issue by andrewufrank** [tdammers/sprinkles#19]
I experiment with Blogg and start to understand more. I have added to a menu item a submenu item but would like this to be drop down (not a horizontal list as currently). I looked into the renderMenu macro and the style sheet and have the impression that both need to be changed to render a submenu differently than the first and to add corresponding styles. Is there a better way?

sorry to add "suggestions" and general discussion to the issues - where would be the appropriate forum? 

I like it a lot (except the caching issue I do not understand)!

**Comment by tdammers** [comment]
> I experiment with Blogg and start to understand more. I have added to a menu item a submenu item but would like this to be drop down (not a horizontal list as currently). I looked into the renderMenu macro and the style sheet and have the impression that both need to be changed to render a submenu differently than the first and to add corresponding styles. Is there a better way?

Hmm, not really, no. Dropdown menus being difficult is kind of a limitation of the web platform, it's not intrinsic to Sprinkles or Ginger. And to avoid the associated complexity, and / or dependencies on CSS frameworks like Bootstrap, I opted to do it this way in the Blogg example.

> sorry to add "suggestions" and general discussion to the issues - where would be the appropriate forum?

Ah, hmm, that's a bit of a sore spot unfortunately. On the one hand, a proper forum-like communication channel would be great; on the other hand, I kind of hate slack and its lookalikes with a passion, and I really really don't feel like maintaining a server running lousy forum software that requires constant hand-holding and policing. You can of course always e-mail me (tdammers@gmail.com), or ping me on freenode (I hang out on #haskell and a few other channels, my nick is online almost 24/7 even though I don't always respond immediately), although I guess leaving a digital paper trail has its advantages too.

If you have any ideas, I'm all ears.

> I like it a lot (except the caching issue I do not understand)!

Ah, yes, about that.

So what Sprinkles normally does is this:

- Project files are read once, at startup.
- Templates are read once, at startup.
- Backend data (SQL, files, external API, etc.) is cached according to the caching mechanisms defined in `server.yml`. The default is to not cache anything, but you can enable several caches: filesystem based, in-process, and memcached. Backend data also includes static files served via `static: true` rules.
- For each `data:` item in your project, you can disable caching individually by setting `cache-enabled: false`.
- For each rule in your project, you can set a cache expiration mode: `cache: no-cache` disables caching entirely for this data item, `cache: forever` holds on to it as long as the cache driver allows, and an integer value sets a cache expiration in seconds. This is used to set an `Expires:` header, which tells browsers, proxies, and similar things, how long the response may be cached - Sprinkles doesn't cache responses itself, but you can easily run it behind, say, Varnish, and the expiry headers will work their magic.

When I work on a Sprinkles project, I generally set up a little shell loop using `inotifywait` that automatically kills and restarts the Sprinkles process for me; for more complex projects, I also hook other build processes into that, such as a JS bundler, SASS compilation, image preprocessing, etc.

Hope that helps, and thanks again for your interest.
