### ISSUE TITLE
blog categories

### ISSUE THREAD

**Issue by andrewufrank** [tdammers/sprinkles#20]
I would like to assign categories to my blogs. How could this be done?

I saw in another SSG engine an approach to preceede the markdown text by some yaml to enter things like date, author, ready for publication, categories etc. (separated by ` ----`). Would this work with sprinkles? How to access the corresponding values to feed into ginger? 

I looked into the code. It seems that the parser for markdown would need to change to deal with the two parts and store the result in json format into the BackendData. Would the additional values in YAML then automatically be available in `routes`; I could not  see in the code, where this would be handled but could imagine that JSON would achieve this automatically.  
what are your plans on the subject?

**Comment by tdammers** [comment]
> I saw in another SSG engine an approach to preceede the markdown text by some yaml to enter things like date, author, ready for publication, categories etc. (separated by ----). Would this work with sprinkles? How to access the corresponding values to feed into ginger?

Frankly, I don't know, but I don't think so. `----` is a YAML document separator, while in markdown, it designates a horizontal line. So mixing YAML and markdown like that in the same file doesn't really make sense, though I have seen systems that special-case their markdown readers to support this (which technically makes the input file neither YAML nor markdown).

The Markdown parser used in Sprinkles, Pandoc, does allow for a few fields to be added at the top of the document, by preceding them with `%` signs; the format is very limited though and only allows for some rudimentary, fixed metadata keys. Sprinkles exposes those to Ginger, but the system isn't flexible enough for arbitrary tagging and such.

However, you can do something really close by embedding markdown in YAML. Sprinkles understands YAML just fine; if the extension or MIME-type reported by the backend matches, it will automatically parse backend data as YAML and expose it to Ginger as a suitable data structure (nested hashmaps / lists). You can then simply embed the markdown in one key inside the YAML; using `|`-style strings, this is easy enough on the eyes. The only downside is that you have to explicitly tell Sprinkles to interpret this particular string as Markdown, by passing it through `|markdown` in Ginger. Here's a quick example:

--- hello.yaml ---
```yaml
title: Hello
author: tdammers
body: |
  Here's some **markdown**!
```

--- project.yml ---
```yaml
rules:
  - pattern: '/'
    template: page.html
    data:
    - page: 'file://./hello.yaml'
```

--- templates/page.html ---
```html
<!DOCTYPE html>
<html>
    <body>
        <h1>{{ page.title }}</h1>
        <div>{{ page.body|markdown }}</div>
    </body>
</html>
```

**Comment by andrewufrank** [comment]
I think I will try your suggestion and report back. It seems close to the ideas I have seen, but there, the input was YAML (multiple documents separated) and the second document had no YAML key but used some default. If you are interested, I can find the source (I think it was in simplesite).

**Comment by tdammers** [comment]
Yes, I've seen that approach before - a text file with two sections in it, separated by a YAML-style document separator (`-----`), where the first one is YAML (or JSON in some cases), and the second one is some markup format.

It has some advantages, mostly practical ones; but the big downside is that you now have a file that contains mixed content, which causes a few problems, such as:

- You have to switch parsers halfway through
- There isn't a single MIME type or extension that would be correct for the file (multipart MIME would work, but uses a different format that isn't as human-friendly)
- Syntax highlighters will break (have to choose YAML or Markdown, unless you teach the syntax highlighter to recognize the separator)

Another concern is that Sprinkles doesn't want to tie you into any particular data format - supporting a wide range of content formats and storage technologies is a conscious design decision, we don't want to force authors into any specific markup syntax or data storage format. Other systems make different decisions, sacrificing choice and flexibility for simplicity, and for those systems, a simple custom content format like the one you described does make sense.
