### ISSUE TITLE
small typos

### ISSUE THREAD

**Issue by agreif** [tdammers/sprinkles#3]
on https://sprinkles.tobiasdammers.nl/guide/templates/
1)
(i.e., seeing "special" HTML characters in the output such as &amp; or &gt;.
should be
(i.e., seeing "special" HTML characters in the output such as &amp; or &gt;).

2)
markdown, textile, rst, creole:, Shorthand for pandoc, selecting the input language directly.
should be
markdown, textile, rst, creole: Shorthand for pandoc, selecting the input language directly.

**Comment by tdammers** [comment]
I just moved the documentation into the public `sprinkles` repo, so the markdown sources are now publicly visible.
