### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by ad-si** [tdammers/sprinkles#6]
The https://sprinkles.tobiasdammers.nl website seems to be down.
(Btw: You should add a link to the website to the GitHub description)

**Comment by tdammers** [comment]
Ah yes, the server is apparently down. I've contacted the VPS provider, they probably f*d up (again). Link to website is a good idea.

**Comment by ad-si** [comment]
A link to the website is still a good idea! 😜
I just took me like 5 minutes to find it ^^

**Comment by ad-si** [comment]
Thanks! :grin:
